mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    #password: zzp200217
    password: 200136
    #password: 2002820lzy
#  application:
#    name: login
##  cloud:
#    nacos:
#      discovery:
#        namespace: public
#        server-addr: 127.0.0.1:8848
#        group: spring-cloud
#    loadbalancer:
#      ribbon:
#        enabled: false
#  mvv:
#    resources:
#      add-mapping:true
#ribbon:
#  nacos:
#    enabled: false

server:
  port: 8080


